categorical_features:
  - city
  - gender
  - registered_via
  - reg_year
  - reg_month

default_params:
  objective: binary
  n_estimators: 1000
  verbose: 0

tune_space:
  learning_rate: float, 0.01, 0.2
  num_leaves: int, 31, 256
  max_depth: int, 3, 12
  feature_fraction: float, 0.6, 1.0
  bagging_fraction: float, 0.6, 1.0
  lambda_l1: float, 0.0, 5.0
  lambda_l2: float, 0.0, 5.0
