categorical_features:
  - city
  - gender
  - registered_via
  - reg_year
  - reg_month

default_params:
  objective: binary:logistic
  eval_metric: logloss
  n_estimators: 1000
  use_label_encoder: False
  verbosity: 0
  verbose: false
  early_stopping_rounds: 50

tune_space:
  learning_rate: float, 0.01, 0.2
  max_depth: int, 3, 10
  subsample: float, 0.6, 1.0
  colsample_bytree: float, 0.6, 1.0
  gamma: float, 0.0, 5.0
  reg_alpha: float, 0.0, 5.0
  reg_lambda: float, 0.0, 5.0
